[2023-09-01T19:00:54.972+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trabalho_pipeline.email_consolidado manual__2023-09-01T18:55:42.704080+00:00 [queued]>
[2023-09-01T19:00:54.978+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trabalho_pipeline.email_consolidado manual__2023-09-01T18:55:42.704080+00:00 [queued]>
[2023-09-01T19:00:54.978+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-09-01T19:00:54.986+0000] {taskinstance.py:1382} INFO - Executing <Task(EmailOperator): email_consolidado> on 2023-09-01 18:55:42.704080+00:00
[2023-09-01T19:00:54.990+0000] {standard_task_runner.py:57} INFO - Started process 653 to run task
[2023-09-01T19:00:54.992+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'trabalho_pipeline', 'email_consolidado', 'manual__2023-09-01T18:55:42.704080+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/alomundodag.py', '--cfg-path', '/tmp/tmpkwi0gixn']
[2023-09-01T19:00:54.993+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask email_consolidado
[2023-09-01T19:00:55.023+0000] {task_command.py:415} INFO - Running <TaskInstance: trabalho_pipeline.email_consolidado manual__2023-09-01T18:55:42.704080+00:00 [running]> on host a389df1e50bd
[2023-09-01T19:00:55.071+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='pinheiro.ras@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='trabalho_pipeline' AIRFLOW_CTX_TASK_ID='email_consolidado' AIRFLOW_CTX_EXECUTION_DATE='2023-09-01T18:55:42.704080+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-01T18:55:42.704080+00:00'
[2023-09-01T19:00:55.082+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2023-09-01T19:00:55.082+0000] {configuration.py:1064} WARNING - section/key [smtp/smtp_user] not found in config
[2023-09-01T19:00:55.082+0000] {email.py:270} INFO - Email alerting: attempt 1
[2023-09-01T19:00:55.082+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/email.py", line 77, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2023-09-01T19:00:55.088+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=trabalho_pipeline, task_id=email_consolidado, execution_date=20230901T185542, start_date=20230901T190054, end_date=20230901T190055
[2023-09-01T19:00:55.095+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 15 for task email_consolidado ([Errno 99] Cannot assign requested address; 653)
[2023-09-01T19:00:55.124+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-01T19:00:55.135+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
